!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitmylibpar(f2pysetupfunc)
      use mylibpar, only : matmul
      use mylibpar, only : gauss
      external f2pysetupfunc
      call f2pysetupfunc(matmul,gauss)
      end subroutine f2pyinitmylibpar


